### PR TITLE
Employee2 td

### PR DESCRIPTION
**Pull request by tonidew**
This is the new pull request - after making the changes suggested by Jason.

### CODE REVIEW

**Comment by JasonWeakley** [comment]
:+1:

**Comment by BenCopeland** [comment]
:+1:

**Comment by JasonWeakley** [comment]
Ben, can you show Toni (and me) what you mean? I thought that the width and height needed to be on separate lines, it sounds like you mean they are supposed to be on one line together???

**Comment by BenCopeland** [comment]
I just mean the stylings that are written directly into the html file on the img elements, instead of the css file. They work so it doesnt really bother me, its just not usually common practice.

**Comment by BenCopeland** [comment]
I borrowed some code from the employee page for my employee of the month column, and had trouble writing those into the css so I also left those stylings directly in the html. So nvm on that edit, Im about to submit a pull request for the awards branch and we should be done once they are all merged into the master.

**Comment by JasonWeakley** [comment]
Toni I think that you are good to merge this now.

**Pull request merged**
