### PR TITLE
nav and copyright changes

### PR DESCRIPTION
**Pull request by JasonWeakley**
I updated the nav on the index.html to link to the correct employees.html page, and I changed the footed CSS styling for the copyright text to be font-family Lato.

### CODE REVIEW

**Comment by BenCopeland** [comment]
:+1:

**Comment by JasonWeakley** [comment]
Just realized that the css change I made for the footer will not reflect on your page, can you make the quick change and then push again?

**Comment by BenCopeland** [comment]
done.

**Comment by JasonWeakley** [comment]
:+1:  then we just need Toni, and I have messaged her about your branch. Hopefully we won't have any more changes, and we can all pull from the master tomorrow after all these merges are done.

**Comment by tonidew** [comment]
:+1:

**Pull request merged**
